version: '3'

services:
  reverse-proxy:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - music-service
    ports:
      - 80:80

  music-service:
    build:
      context: music-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_ACCESS_KEY_ID: ASIAWSSDDKFSO42NJO7O
      AWS_SECRET_ACCESS_KEY: 1PrcF9yG/NEwFuGVBFn+82U3pEpK3XRj7QZ79NN+
      AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEAIaCXVzLXdlc3QtMiJHMEUCIQD115cesvCezF9znwfoKNVOmHCq8navwYMo/ve8gCA9PAIgYD6DhPY5Zre+E1HbyOZ8jn1Jyelcn4q7sflwOET6FgEqtwIIWxAAGgw0NTIxODYwMzQ1MzIiDO41CLVmsAxfLSJh5CqUAq9nqf/lv+0ESBXvYU25p7AQaBI3ME3UIFIlZVswGChv6jaopNedlKZdHJNpcRI0aFcp/ynPlwDRFPv2nAGUNeZWblruVO/enBdzRilu0vs0R8fM04AUHT6Q9qjhe+laTYXJETv3ZWTUgUWQSQLMI6WQP0bm+fg4iZXtXReXejOLkFk8DTwwXHbJF7Gpo1uebd4sCHhgwgYv/es2efBhFpBvpHJa3mEW+sRvIpFBlJhZUUiMRwqhi9rdMOExZDTekR82Kt27w24KiDsIdvzrgtrP5/Lkr/41lqO73rVDvtBLDkoLVVoVcEcTEUTXnJfdFoebVH/99V6WM7+5itA6MDlEk19gZXKu4YfokJcebl2HHb03QDDvlruDBjqdAVWBdfoLAM7vD/RSpDB4+MwLhjmWfwJstEpOpXMHPyjExlgLm7ZZduLPBtlpDttfaaPngf32dYRDnEYvJ2K/wLa1+hDWib5boCY7JGgCd86DJtE5RGK2jEcytlPO9NUM0ilKN1+ZYD2zSxt2Am4GnLIyvmgm1xe4R77Z230stUWHq38jlhCAyMO4+LgJCkG4wPI/Y8GHKwT8BhdH3ug=
    ports:
      - 8080:80
    restart: on-failure

  artist-service:
    build:
      context: artist-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8081:80
    restart: on-failure

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hardhub
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: