version: '3'

services:
  reverse-proxy:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - music-service
    ports:
      - 80:80
  
  keycloak-mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: keycloak-mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - keycloak-mysql

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  music-service:
    build:
      context: music-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_ACCESS_KEY_ID: ASIAWSSDDKFSENRA3P64
      AWS_SECRET_ACCESS_KEY: 879IV2PKGkwTIY5b7V2UKYM3xbE1x0dybQAkZ6Vc
      AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEHcaCXVzLXdlc3QtMiJGMEQCIBU1UwDkNKmjZd6eALCzowuYrXtdziA17/garbhd/WFdAiAh1X5c641JrsY3cV5YEuQdU9wdIFC9DwWUZzJ18/wHUirAAgjv//////////8BEAAaDDQ1MjE4NjAzNDUzMiIMrfEOnNC/pwiup/DMKpQCSGxVnvEuqaaD8RoHJ4Dp/FHb0MCH10EgLM1fBltRMkVkAw4MDsdnoqKsefEY/Y2P1q2Ub9qNTtlPubzyuBBXwCrm41YR2J0nnnKF/bmWcUwifdi/D3050kpFcym0zLu+c10UGYR2f8mtsVssCes+hdEB0kjSevT5N8fg6jyQJXOYh9xpG5xUMSGZlAiDXJp6wIxm4cWO7GfPsU2ajnZgEuu45X54QkRI9EvXMJc40wUseRI4dGKwiZtUWrYyUJxZyKOW2DjubcDB+lAiZgbnJoUUzCZWNEroR1T9dZLpUJ6+EDbrDbQ0P83Mk3kETh8xH6dTYctpGXVafJRcWz+Np5g1GMiAmRLLpFOFUSLE2MeRYxQiMKSwxYQGOp4B3IAjapp0KX3Eo50+z01DHvCYjj48mFvNRMBGPVTuTd++ouxJ28vL8XlQr6NDIu0LEKueJMEG5Pyuc4B0yVRlXCU5N0Kvo/tr7cB2yiQ7hk6Q69o6lky1/iczDVH4/x8/imy+bX5U6j3eic/YfyHFa7lS9sshGhuT7RYWr/TM93QHhxvUX/yYQp6bh60VTlayoNpI8/As3+Kqypq/bu4=
    ports:
      - 8081:80
    restart: on-failure
    depends_on:
        - keycloak

  artist-service:
    build:
      context: artist-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8082:80
    restart: on-failure
    depends_on:
      - keycloak

  playlist-service:
    build:
      context: playlist-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8083:80
    restart: on-failure
    depends_on:
      - keycloak
      - playlist-mysql
  
  playlist-mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - playlist_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playlist
      MYSQL_USER: playlist
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hardhub
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
  mysql_data:
      driver: local
  playlist_data: