version: '3'

services:
  reverse-proxy:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - music-service
    ports:
      - 80:80

  music-service:
    build:
      context: music-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_ACCESS_KEY_ID: ASIAWSSDDKFSEUKLPFUH
      AWS_SECRET_ACCESS_KEY: GANcW5c7elNSvF7yfBh9mB4Bii9hAyq04oyWyPTg
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEHEaDEJbKgZ0EbWh/rMQRyLOAQs9+XDg4joyKL16CgHPs2xXENXn633bkisA99cJtbI1cUoMCPdi+yctl8qhmkBPaujbbf+hMhGLwb+pLWorR5TQz0rubzl+MWWspi1a5RTedwvBusI83XZVltO7JntNyAj11HPMsEktl7k1OxWyqWg5NvHSc9YIoAtH1aswUX2/KsxqGH80snr1J9wHBNupq7Z1XcySmYS5jRhqGyyLwbtSuZMRD/oCyeVAfzPSrmMgIG/C5gqdp5AZPjLLAS2G4O9H8ehmvY0IlAhoRvD1KJLPl4MGMi1DQqNjRMABEqWKvaNCwcQYHGK/wU8CpGUctph4sABTmIRhR9vDRZQWn78cTws=
    ports:
      - 8080:80
    restart: on-failure

  artist-service:
    build:
      context: artist-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8081:80
    restart: on-failure

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hardhub
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: