version: '3'

services:
  reverse-proxy:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - music-service
    ports:
      - 80:80

  music-service:
    build:
      context: music-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_ACCESS_KEY_ID: ASIAWSSDDKFSKUE2R67O
      AWS_SECRET_ACCESS_KEY: LNQwbSM/X271PFZP+8g+SSLmPJKeycdiFMs+yjHs
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEGoaDAsSh6XyVP/DTBcpACLOAXARKitHESX3uXGn/sPQN1R2bwclYdGwC63+PuUnv7rUjb8seLfEgM1O0tBRcoL8j1CDsT0PtCTy3yXEZzw6LaBdGasiyJyak9wx8+Xnh+Y6wBBDccRJ4W2fF3E+lvWR0km1EZvv5od/HQcob/Wl73lL4WOOkBFXYA12SaPcV2LhMXiJyLC1/GtLuWJ1yzg2RN9poTna4YBkPNpxTKBOqmdDXf+ZSVidVcrG+qZM8vvUm3eGuVGoAhMBf9LX+LeKnf/NKpY3hzAsxrDC2HrYKLuEloMGMi2I9VBoX36coIRf+4HrsF4ZJVsowuJZrGB+gwq62B/nBw0EiyaUHUna8SXez2k=
    ports:
      - 8080:80
    restart: on-failure

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hardhub
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: