version: '3'

services:
  reverse-proxy:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - music-service
    ports:
      - 80:80

  music-service:
    build:
      context: music-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_ACCESS_KEY_ID: ASIAWSSDDKFSPASHPWBI
      AWS_SECRET_ACCESS_KEY: y2Bl+A0NTK4MqqhYJPAbxW3SUV2digXAMruEuZUy
      AWS_SESSION_TOKEN: FwoGZXIvYXdzED0aDO69p0yOMq5kGkfTUyLOARTBvtS0cWxvnKqOla0h7fozxpXMnxRdZ0odx9x6KMUY7GH/SRoqEsLGc50mfEn/ljj1Kcdbjr3z+1t8/ijSaH6LIhkadcpMtoLi0xfQgl92cTPYxBmPaTpiXfdwFl8kzd9f+2+gijTlAXvT0mT9V9xBSEn7jQA/Q2zzaNx6cuXvngYWb/jq83NiDpY3EcsjyjCMSUxJg42dr6puIunQuGN72MOCII/b5NJvAiIpcuXG7d2hGDUR0OOScug1waKclruumyt2ZcTNxRwYMx7GKIinjIMGMi0e3G8JVFSmFEM+0zNG7YjWiPrx/4RYGC9FO2QO26Vhh77aowBoLCp6h072Djk=
    ports:
      - 8080:80
    restart: on-failure

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hardhub
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: