version: '3'

services:
  reverse-proxy:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - music-service
      - artist-service
      - playlist-service
    ports:
      - 80:80
  
  keycloak-mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: keycloak-mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - keycloak-mysql

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  music-service:
    build:
      context: music-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_ACCESS_KEY_ID: ASIAWSSDDKFSOL3MWCV2
      AWS_SECRET_ACCESS_KEY: YJpCJhvsBcjENWgF0xaVBVbBsItTbQX4z16qJUYb
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEPr//////////wEaDOEirirxnxMwqZzuZyLOAXNWh7KBK32k3FG39NdrX6hiJeVhrN7z978hl3h/QDpWEluEIjn49kWaA66ZRYgtEai3dUh/mFrg01J5ljdQYhwL/oJ1xPZbVVN/epJKFjExVrtc5kYr5Xh0VSI0LBhJ0sZNbypd4wpGV3JdqxZqMYFmB8yZ7MnYHMkdE6soNy3Jx5iepbQ9+cwtl53V5DeZ/Daxwjazgy5X0ursTbAv7GEZCa16XnyqCFloJcrNw91JxYcG7yNwbTNGudFe6kANnwZTFZHAGFMOOMsMm3TiKISdh4YGMi3hUrNK1rLqlK5E6klpweKcnfqHmp3NpdTArgM9969/gZWK9SRsk2fWp2hRdmk=
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - 8081:80
    restart: on-failure
    depends_on:
        - keycloak
        # - kafka
        - database

  artist-service:
    build:
      context: artist-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment: 
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - 8082:80
    restart: on-failure
    depends_on:
      - keycloak
      - database

  playlist-service:
    build:
      context: playlist-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment: 
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - 8083:80
    restart: on-failure
    depends_on:
      - keycloak
      - playlist-mysql
  
  playlist-mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - playlist_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playlist
      MYSQL_USER: playlist
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hardhub
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: forget-artist:2:1
    ports:
      - 9094:9094
    restart: always

volumes:
  mongodb_data_container:
  mysql_data:
      driver: local
  playlist_data:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local