version: '3'

services:
  reverse-proxy:
    build:
      context: gateway
      dockerfile: Dockerfile
    depends_on:
      - music-service
    ports:
      - 80:80
  
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mysql

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  music-service:
    build:
      context: music-service
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      AWS_ACCESS_KEY_ID: ASIAWSSDDKFSDL5W434S
      AWS_SECRET_ACCESS_KEY: 2qxs/HkyF2akDaG8kK/TybwxiVLcAabRcNBmLPPF
      AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEFAaCXVzLXdlc3QtMiJHMEUCIQC4QOkNnhYNtfZkp+m+ODh/KF4MGzuhyZr91rKtut6jeQIgT37E9p45Mwy20EpzHkPLydzAORM2Du/t3XNYNaO6z/gqwAIIuf//////////ARAAGgw0NTIxODYwMzQ1MzIiDNCbSxYtpS3MVK2/0iqUAjsHb1tuMXBfvcHFElSIdws+wrbBN4XvVTdTqWfeFWmCBvBgJhGT7jgB53PjxNBS3LO0hMFez1Psh415Fsj5o/YCSfk55LIMrf8QQE9PZw2vy+CIAlhmwm/B9PAIPqidy3TQ2eh1avAE78n5iU8/IK46xGZVg89A5bn9WKyXH/r5M9PlkZ4ZrxMZ4fc071Z2Xc7lPxYO6DUen2+FTFqimrMkqwKlR3nbIFBeRNEdzh+0GJKc+a6LdldSH/phvwBUEbpFsSH3uSEfQVY2AMxXmrGnMiYBSZ6gW0G1LpXD0zRjOsnwdUsPzfwWN7IoJrnp/MO5EjyerqXu9uH0zcBZNE1GYHHvFzK3meHNATU2jLRq/hTvCTDd0ISEBjqdAavEaM3JGO565xM2YsmCWD+0JRrgZIfygmWFMIghW9DMEe8AGxmIJZ5y7J/McRFQM+H0XcG9PwBqG6oFS9/t+KUeQg6OvUdi5yGe1LgI52Tgfy4zYhhjzjRM1OKE9Pxp1MTd6hl56Cg4UekG5CTlBZnxLMv1ctCuGHeR32SvlZKpHIPkbOMnFSQ/MUOg4Rg55IxhY8Ax1FBQvaiHRD4=
    ports:
      - 8081:80
    restart: on-failure
    depends_on:
        - keycloak

  artist-service:
    build:
      context: artist-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8082:80
    restart: on-failure
    depends_on:
      - keycloak

  playlist-service:
    build:
      context: playlist-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8083:80
    restart: on-failure
    depends_on:
      - keycloak

  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=hardhub
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
  mysql_data:
      driver: local