apiVersion: apps/v1
kind: Deployment
metadata:
    name: music-service
    labels:
        app: music-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: music-service
    template:
        metadata:
            labels:
                app: music-service
        spec:
            containers:
            - name: music-service
              image: docker.pkg.github.com/rickverkuijlen/hardhub/hardhub_music-service:v1
              ports:
              - containerPort: 9090
              env:
              - name: QUARKUS_MONGODB_CONNECTION_STRING
                valueFrom:
                  configMapKeyRef:
                    name: music-service-configmap
                    key: database_url
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  configMapKeyRef:
                    name: music-service-configmap
                    key: aws_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  configMapKeyRef:
                    name: music-service-configmap
                    key: aws_secret_access_key 
              - name: AWS_SESSION_TOKEN
                valueFrom:
                  configMapKeyRef:
                    name: music-service-configmap
                    key: aws_session_token
---
apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  selector:
    app: music-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090