apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        app: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
              - name: mysql
                image: mysql:latest
                ports:
                - containerPort: 3306
                volumeMounts:
                - mountPath: /var/lib/mysql
                  name: k8s-mysql-storage
                env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: password 
            volumes:
            - name: k8s-mysql-storage
              emptyDir: {}
                
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306