apiVersion: apps/v1
kind: Deployment
metadata:
    name: playlist-service
    labels:
        app: playlist-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: playlist-service
    template:
        metadata:
            labels:
                app: playlist-service
        spec:
            containers:
            - name: playlist-service
              image: docker.pkg.github.com/rickverkuijlen/hardhub/hardhub_playlist-service:v1
              ports:
              - containerPort: 9092
              env:
              - name: QUARKUS_DATASOURCE_JDBC_URL
                valueFrom:
                  configMapKeyRef:
                    name: playlist-configmap
                    key: database_url
              - name: QUARKUS_DATASOURCE_PASSOWRD
---
apiVersion: v1
kind: Service
metadata:
  name: playlist-service
spec:
  selector:
    app: playlist-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9092